### ISSUE TITLE
automatic devstack reload does not pick up page scoped templates

### ISSUE THREAD

**Issue by doobox** [yourhead/s3#170]
Noticed that any changes(edits) I make in a page scoped CSS template are not updated inside RW without a restart.
Each scoped template changes(edits) are indeed working as expected and updating inside RW.

**Comment by doobox** [comment]
Also just noted that a .devstack plist edits / changes are not update in RW either.

**Comment by joeworkman** [comment]
I just thought that I would comment on some behavior that I am seeing for this. It looks as if page scoped templates may be getting loaded. However, only inside Edit Mode. If you preview the page, the old version is still used. 

I noticed that my page scoped CSS was indeed getting reloaded because styles were updating in Edit Mode. However, once I previewed the page, the changes were gone.

**Comment by yourhead** [comment]
i suspect it should be much improved in the next build.  i fixed three independent bugs which probably all contributed to various behaviors here.

**Comment by joeworkman** [comment]
This still does not seem to be working. I have tested page scoped HTML, CSS and JS templates. None of them seem to take affect until I restart RapidWeaver.

**Comment by joeworkman** [comment]
Just to make sure that I was not going crazy, I built this super simple example stack... https://infinit.io/_/34rV8aN

If you any any of the contained page scoped templates, the changes seem to appear in Edit Mode but no preview. A simple thing to change is the background-color in the CSS file.

**Comment by yourhead** [comment]
1. add stack to page
2. preview stack. note green background
3. change green to red in page.css
4. preview stack. note still green

works as expected in edit mode. bug only exists in preview
