### ISSUE TITLE
Cannot show stack media in Finder

### ISSUE THREAD

**Issue by joeworkman** [yourhead/s3#601]
It used to be possible to right click on a image media in the Stacks library and show in Finder. This is no longer possible. 

Many time users would like to tweak an image in an external editor before adding it to the page. A better solution would be the ability to simply drag and drop an image media into Finder. It would simply copy that image from the stack into the Finder.

**Comment by yourhead** [comment]
This was an intentional change.  Some users found it confusing to have Show in Finder open to a folder that's buried inside of a stack bundle or in some cache folder somewhere.

But it's also confusing to disable the Show in Finder menu...

I do like the drag and drop idea.  I think that's a reasonable request.  I'm going to file it separately.

**Comment by yourhead** [comment]
ok, i just tried this for fun -- basically enabling the functionality for everything.

it seems pretty obvious why i disabled Show in Finder now...   there are a lot of places where it either doesn't make sense at all or it creates more problems than it solves  (partials!! omg)

i think we can enable this for some more things, but will require some real work.  going to put it on the list for 3.3.0

**Comment by joeworkman** [comment]
Fixed or no go?

**Comment by yourhead** [comment]
still not sure if this is the right thing. but for now i've just thrown the switch to ON ALWAYS. i think it has the potential to cause even more confusion since it tends to open up bundles and things that a user probably shouldn't be messing with -- but ¯\_(ツ)_/¯ let's see how it goes.

**Comment by yourhead** [comment]
it'll be in beta 2
